### ISSUE TITLE
Code-style вышел из чата

### ISSUE THREAD

**Issue by FazziCLAY** [MrY122/MyMontager#1]
Функции и методы принято в питоне именовать с малеьнокй буквы, если требуется разделение используется нижнее подчёркиване (*Example*: do_not_puke)

С большой бувквы и разделением через изменение регистра принято называть классы (*Example*: DoNotPukerUtil)

**Comment by MrY122** [comment]
То чувство, когда code style в чат и не заходил... 

Ладно, в следующем коммите поправлю
